### PR TITLE
EASYOPAC-1206 - Update styles for node blog nodes.

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**
https://inlead.atlassian.net/browse/EASYOPAC-1206

### CODE REVIEW

**Comment by guddo** [comment]
@mihaelad How is this different from https://github.com/easySuite/ding_blog/pull/35?

**Comment by NicolaeGrigoriu** [comment]
@guddo I guess they fix the same thing, we can use only one PR and close the other one and then to see what else needs to be fixed so it looks good.

**Comment by guddo** [comment]
It's solved in 2 different ways, and I think you 2 should discuss what is better to do. @NicolaeGrigoriu @mihaelad

**Comment by NicolaeGrigoriu** [comment]
Closed this PR in favor of https://github.com/easySuite/ding_blog/pull/35. Other styles will be added there by @mihaelad if needed.

**Pull request closed without merging**
