### PR TITLE
EASYOPAC-1224 - Blog improvements.

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**
https://inlead.atlassian.net/browse/EASYOPAC-1224

a. use the easyddb frontpage layout;
b. ajaxify views;
c. migrate blog lists from nodelist to view;
d. export pathauto settings;
e. display author image on related blogs;
f. display author name on teaser display.

### CODE REVIEW

**Review by guddo — APPROVED** [review]
I'm gonna approve this, even though I don't think we should use the easyddb layout. /cc @NicolaeGrigoriu

**Comment by NicolaeGrigoriu** [comment]
@guddo what other layout should be used in order to have separate color sections for each pane?

**Comment by guddo** [comment]
Just the default ding2 panel. However then we can't have a left side menu selecting categories/authors.

**Comment by NicolaeGrigoriu** [comment]
Should I update layout so the ding2, Ding frontpage layout 1 is used?

**Review by OIOIOOOI — APPROVED** [review]

**Pull request merged**
